name: Collaborative CTF Environment

# Only run when manually triggered
on: 
  workflow_dispatch:
    inputs:
      webhook_url:
        description: Webhook URL (e.g. from https://webhook.site) for posting tmate info
        required: false

jobs:
  start_server:
    name: Install packages and start the collaborative CTF server
    runs-on: ubuntu-latest
    steps:
      - name: Install (and upgrade) packages
        run: |
          sudo apt-get update && sudo apt-get --yes upgrade
          # TODO: add other packages for CTF stuff
          PACKAGES=(
            binutils
            curl
            wget
            gcc
            tmux
            vim
            nmap
            htop
            tor
          )
          sudo apt-get --yes install ${PACKAGES[@]}
          
      - name: Set up my dotfiles
        run: |
          cd
          git clone https://github.com/jstrieb/dotfiles.git
          cd dotfiles
          sed -i "s/INSTALL_PACKAGES=true/INSTALL_PACKAGES=false/g" install.sh
          sed -i 's/bind \\\\/bind \\/' .tmux.conf
          chmod +x install.sh
          bash install.sh
          cp ~/.tmux.conf ~/.tmate.conf
          
      - name: Install tmate (reverse shell)
        run: |
          cd
          sudo apt-get --yes install xterm
          ssh-keygen -f ~/.ssh/id_rsa -N ""
          wget -O "tmate.tar.xz" "https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz"
          tar -xvf "tmate.tar.xz"
          echo
          
      - name: Run tmate and send login info via a webhook if one is entered
        run: |
          set -m  # For some reason bash doesn't have job control enabled by default????
          ~/tmate-2.4.0-static-linux-amd64/tmate -F > ~/tmate_info.txt &
          sleep 5
          cat ~/tmate_info.txt
          curl --request POST --header "Content-Type: text/plain" --data @~/tmate_info.txt ${{ github.event.inputs.webhook_url }} || true
          fg
          
      - name: Clean up
        run: |
          echo Done!
